const { contextBridge, ipcRenderer } = require("electron");

function subscription(channel, listener) {
  const wrapped = (_event, value) => listener(value);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
}

contextBridge.exposeInMainWorld("codexWebLauncher", {
  snapshot: () => ipcRenderer.invoke("launcher:snapshot"),
  tasks: () => ipcRenderer.invoke("launcher:tasks"),
  taskSettings: value => ipcRenderer.invoke("launcher:task-settings", value),
  taskKey: value => ipcRenderer.invoke("launcher:task-key", value),
  taskKeyRemove: () => ipcRenderer.invoke("launcher:task-key-remove"),
  taskCheck: () => ipcRenderer.invoke("launcher:task-check"),
  taskPreview: input => ipcRenderer.invoke("launcher:task-preview", input),
  taskStart: input => ipcRenderer.invoke("launcher:task-start", input),
  taskMode: (id, mode) => ipcRenderer.invoke("launcher:task-mode", id, mode),
  taskAction: (id, action, feedback) => ipcRenderer.invoke("launcher:task-action", id, action, feedback),
  taskApproval: (id, requestId, decision) => ipcRenderer.invoke("launcher:task-approval", id, requestId, decision),
  taskFolder: () => ipcRenderer.invoke("launcher:task-folder"),
  taskExport: id => ipcRenderer.invoke("launcher:task-export", id),
  onTasksChanged: listener => subscription("launcher:tasks-changed", listener),
  setLanguage: (language) => ipcRenderer.invoke("launcher:set-language", language),
  setTheme: (theme) => ipcRenderer.invoke("launcher:set-theme", theme),
  openSocial: (target) => ipcRenderer.invoke("launcher:open-social", target),
  completeOnboarding: (language) => ipcRenderer.invoke("launcher:complete-onboarding", language),
  openExternal: (url) => ipcRenderer.invoke("launcher:open-external", url),
  copyText: (value) => ipcRenderer.invoke("launcher:copy-text", value),
  setBrowserBounds: (bounds) => ipcRenderer.invoke("launcher:browser-bounds", bounds),
  setBrowserSurfaceActive: (active) => ipcRenderer.invoke("launcher:browser-surface-active", active),
  showBrowser: () => ipcRenderer.invoke("launcher:browser-show"),
  hideBrowser: () => ipcRenderer.invoke("launcher:browser-hide"),
  navigateBrowser: (action) => ipcRenderer.invoke("launcher:browser-navigate", action),
  zoomBrowser: (action) => ipcRenderer.invoke("launcher:browser-zoom", action),
  selectBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-select", tabId),
  closeBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-close", tabId),
  openLogin: () => ipcRenderer.invoke("launcher:browser-login"),
  openPasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login"),
  continuePasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login-continue"),
  logoutChatGpt: () => ipcRenderer.invoke("launcher:browser-logout"),
  dismissSessionReminder: () => ipcRenderer.invoke("launcher:session-reminder-dismiss"),
  smokeTest: () => ipcRenderer.invoke("launcher:browser-smoke"),
  verifyMcp: () => ipcRenderer.invoke("launcher:mcp-verify"),
  doctor: () => ipcRenderer.invoke("launcher:doctor"),
  cancelTurns: () => ipcRenderer.invoke("launcher:cancel-turns"),
  uninstallIntegration: () => ipcRenderer.invoke("launcher:uninstall-integration"),
  setupCore: () => ipcRenderer.invoke("launcher:setup-core"),
  setupMcp: (input) => ipcRenderer.invoke("launcher:setup-mcp", input),
  setMcpStep: (step) => ipcRenderer.invoke("launcher:set-mcp-step", step),
  setAutostart: (enabled) => ipcRenderer.invoke("launcher:autostart", enabled),
  setBiggerContext: (enabled) => ipcRenderer.invoke("launcher:bigger-context", enabled),
  dismissBiggerContextRecommendation: () => ipcRenderer.invoke("launcher:bigger-context-recommendation-dismiss"),
  setPreference: (key, value) => ipcRenderer.invoke("launcher:set-preference", key, value),
  setSidebarState: (state) => ipcRenderer.invoke("launcher:sidebar-state", state),
  logs: (limit) => ipcRenderer.invoke("launcher:logs", limit),
  exportLogs: () => ipcRenderer.invoke("launcher:export-logs"),
  usageSummary: () => ipcRenderer.invoke("launcher:usage-summary"),
  exportUsage: () => ipcRenderer.invoke("launcher:export-usage"),
  resetUsage: () => ipcRenderer.invoke("launcher:reset-usage"),
  installUpdate: () => ipcRenderer.invoke("launcher:update-install"),
  windowState: () => ipcRenderer.invoke("launcher:window-state"),
  windowControl: (action) => ipcRenderer.send("launcher:window-control", action),
  onWindowStateChanged: (listener) => subscription("launcher:window-state-changed", listener),
  onStateChanged: (listener) => subscription("launcher:state-changed", listener),
  onBrowserState: (listener) => subscription("launcher:browser-state", listener),
  onOperation: (listener) => subscription("launcher:operation", listener),
  onLog: (listener) => subscription("launcher:log", listener),
  onUpdateState: (listener) => subscription("launcher:update-state", listener),
  onNavigate: (listener) => subscription("launcher:navigate", listener),
});
